-- MySQL Script generated by MySQL Workbench
-- Sat Aug 13 10:39:59 2016
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ionicbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ionicbook` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ionicbook` ;

-- -----------------------------------------------------
-- Table `ionicbook`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ionicbook`.`USER` (
  `user_id` INT NOT NULL,
  `user_account` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
